baseURL = 'https://geekstech.blog/'
languageCode = 'en-us'
title = 'GeeksTech'
theme = "m10c"
tableOfContents = true
defaultContentLanguage = 'ua'
defaultContentLanguageInSubdir = true

[languages]
  [languages.ua]
    contentDir = 'content/ua'
    disabled = false
    languageCode = 'uk-UA'
    languageDirection = 'ltr'
    languageName = 'Ukrainian'
    title = 'Блог Вуйка Боба'
    weight = 1
    [languages.ua.params]
      subtitle = 'Усяке навколотехнічне'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Wujko Bob blog'
    weight = 2
    [languages.en.params]
      subtitle = 'Geeks tech stuff'

[params]
  # Author
  author = "Bob"

  # Description
  description = "IT/cyber/tech geek"

  #avatar = "avatar.jpg"
  avatar = "avatarshelter.png"

  favicon = "/images/favicon.ico"

  # Social links
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/BlackVS"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/BlackVS/"
  [[params.social]]
    icon = "brand-youtube"
    name = "Youtube"
    url = "https://www.youtube.com/@WujkoBobShelter"


[params.style]
#  darkestColor = "#d35050"
#  darkColor = "#212121"
#  lightColor = "#f5e3e0"
#  lightestColor = "#f5f5f5"
  primaryColor = "#7f7f7f"